### ISSUE TITLE
Getting contents of a file in drive using DriveItem getContent()

### ISSUE THREAD

**Issue by AmudhaNila** [davidmoten/odata-client#128]
Hi David,

I am trying to get the raw contents of a file in drive using the DriveItem getContent() method. But even though the file has contents, it is null in the DriveItem class. getContent() hits a null pointer exception even though the graph API on the itemid /content works.

```
Optional<StreamProvider> sp = graphService
                    .drives(driveId)
                    .items(itemId)
                    .get()
                    .getContent();
```

Can you please confirm the way to use this method? Am I missing something?

Thanks

**Comment by davidmoten** [comment]
Please show the stack trace of the NullPointerException.

**Comment by davidmoten** [comment]
Also put on debug logging so we can see the metadata returned with the Drive Item.

**Comment by davidmoten** [comment]
Looking at https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0 it appears that microsoft in their wisdom (!!!) have chosen to use non-standard metadata fields for the download url (`@microsoft.graph.downloadUrl`). Seeing the DriveItem json returned (or print out item.getUnmappedFields().entrySet()) would be great, thanks.

**Comment by davidmoten** [comment]
You can try your code again with 0.1.53-SNAPSHOT if you like (build latest master branch) as I've added a bit of a bandaid to use `@microsoft.graph.downloadUrl` if it exists (and the expected OData metadata field of `content@odata.mediaReadLink` is not present).

**Comment by davidmoten** [comment]
Note also from README.md: https://github.com/davidmoten/odata-client#streams (add .metadataFull() before calling .get())

**Comment by AmudhaNila** [comment]
Hi David,

I tried with the 0.1.53-SNAPSHOT but still facing same issue (stack trace at the end).  Attaching the Drive Item json for your ref.
[driveItem.txt](https://github.com/davidmoten/odata-client/files/6391726/driveItem.txt)


When I tried calling .metadataFull() before calling get(), I get a different error though. Adding it seems to add an extra /$value at the end of the request url :

> getStream returned HTTP 400
> url=https://graph.microsoft.com/v1.0/drives('b%219BWQkwb6BU-FGYNtnMEvuM_f_Djq5I9MvNVLQbVWhmdpm4AZrhScTbapjoB5OoNJ')/items('01OKI7IIFLATICNLEZLVFKWT5F7TT7C2E4')/content/%24value
> headers=[]
> response:
> {"error":{"code":"BadRequest","message":"The request URI is not valid. The segment 'content' must be the last segment in the URI because it is one of the following: $ref, $batch, $count, $value, $metadata, a named media resource, an action, a noncomposable function, an action import, a noncomposable function import, an operation with void return type, or an operation import with void return type.","innerError":{"date":"2021-04-28T12:16:40","request-id":"77c43951-83e2-4f99-a626-e072c1b541eb","client-request-id":"77c43951-83e2-4f99-a626-e072c1b541eb"}}}

Here is the stack trace of the null pointer exception without .metadataFull()

> java.lang.NullPointerException: null
> 	at com.github.davidmoten.odata.client.Path.addSegmentDelimiter(Path.java:52) ~[odata-client-runtime-0.1.49.jar:na]
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Error has been observed at the following site(s):
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ HTTP GET "/api/o365/v1/drives/b!9BWQkwb6BU-FGYNtnMEvuM_f_Djq5I9MvNVLQbVWhmdpm4AZrhScTbapjoB5OoNJ/items/01OKI7IIFLATICNLEZLVFKWT5F7TT7C2E4/content" [ExceptionHandlingWebHandler]
> Stack trace:
> 		at com.github.davidmoten.odata.client.Path.addSegmentDelimiter(Path.java:52) ~[odata-client-runtime-0.1.49.jar:na]
> 		at com.github.davidmoten.odata.client.Path.addSegment(Path.java:42) ~[odata-client-runtime-0.1.49.jar:na]
> 		at com.github.davidmoten.odata.client.internal.RequestHelper.createStreamForEdmStream(RequestHelper.java:463) ~[odata-client-runtime-0.1.49.jar:na]
> 		at odata.msgraph.client.entity.DriveItem.getContent(DriveItem.java:499) ~[odata-client-msgraph-0.1.49.jar:na]

**Comment by davidmoten** [comment]
Thanks for the details @AmudhaNila. I'm relieved to see the `content@odata.mediaReadLink` field and `$value` should not be appended to a stream property (only media entities) so I'll fix that.  I'll also fix the NPE. I assume the `content@odata.mediaReadLink` only turns up when `.metadataFull()` is added?

**Comment by davidmoten** [comment]
I've applied the fixes in PR # 128.

Can you build 0.1.53-SNAPSHOT again from master and try that call again please?

**Comment by davidmoten** [comment]
I've released [0.1.53](https://github.com/davidmoten/odata-client/releases/tag/0.1.53) with these fixes, can you try that version please?

**Comment by davidmoten** [comment]
I've also raised https://github.com/microsoftgraph/microsoft-graph-docs/issues/12534 to fix the graph documentation.

**Comment by AmudhaNila** [comment]
Hi David,

I tested with 0.1.53 and the fix works as expected. I am now able to get the stream provider of contents of a drive item using 
`graphService
                    .drives(driveId)
                    .items(itemId)
                    .metadataFull()
                    .get()
                    .getContent();` 

Thanks a lot.

**Comment by davidmoten** [comment]
No worries. Thanks for the report. I hadn't bumped into stream properties yet in my own use cases so was an untested path.

**Comment by davidmoten** [comment]
By the way, the need to specify metadataFull() before getting a stream is an annoying gotcha that will probably bite lots more people. I'm thinking I might default to full metadata for any media entity or entity with a stream property. I'll raise a PR for this soon, comments welcome.
