### ISSUE TITLE
add unit test for setting fields to null using generated code

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/odata-client#13]
#7 contained a fix for persisting field changes to null from @badfish69 but we didn't have a unit test using code generated from metadata. Let's add one.

**Comment by davidmoten** [comment]
I'm glad I raised this, we do have a problem because in generated code the classes are annotated with `@JsonInclude(Include.NON_NULL)`.

**Comment by badfish69** [comment]
> I'm glad I raised this, we do have a problem because in generated code the classes are annotated with `@JsonInclude(Include.NON_NULL)`.

Ah - that would be an issue.  I have to admit, that I haven't tried the new version of this bit of code in anger yet, so hadn't noticed that it probably doesn't work.
