### ISSUE TITLE
There is no Odata library to list site permissions as mentioned in Microsoft documentation "https://docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&tabs=java"

### ISSUE THREAD

**Issue by nashikanta** [davidmoten/odata-client#138]

**Comment by davidmoten** [comment]
Can you be more specific about the problem? The msgraph client has this available (which mirrors the documentation in the link you gave):

```java
client.sites("123").permissions().forEach(System.out::println);
```

**Comment by nashikanta** [comment]
Hi David, I tried with  graphService.sites(siteId) but I couldn't get the permissions().

**Comment by davidmoten** [comment]
Are you using the latest version 0.1.55? what do you mean? you got an error? what error?

**Comment by nashikanta** [comment]
Thanks David. I got the library in latest version 0.1.54

**Comment by davidmoten** [comment]
Sorted? Close the issue if you are, thanks.

**Comment by nashikanta** [comment]
yes sorted. Thanks David
