### ISSUE TITLE
How to get partial range of content of a drive item(file)

### ISSUE THREAD

**Issue by Pavani-Y** [davidmoten/odata-client#152]
Hi David,
We have implemented code to get item content as per you suggestion earlier in issue https://github.com/davidmoten/odata-client/issues/128. 
  _Optional<StreamProvider> sp = graphService
                    .drives(driveId)
                    .items(itemId)
                    .get()
                    .getContent();_
Now i'm looking to get partial range of contents. I need to give Range header, to same get content api. Can you please help with how to give range headers to it.

Thanks,
Pavani

**Comment by davidmoten** [comment]
Before you hit the first `.get()` you should be able to set headers. Let me know if you can't.

**Comment by davidmoten** [comment]
I just tried it:

```java
client.drives("ABC")
        .items("123")
        .requestHeader("Range", "blah") 
        .requestHeader("Thing", "Stuff") 
        .get()
        .getContent();
```

**Comment by Pavani-Y** [comment]
Sure Thanks David. Will try this.

**Comment by Pavani-Y** [comment]
Hi David,
I tried as mentioned below. But it gives full content and 200 response. But graph api to get content, gives partial content when range headers are given with 206 Partial content as response. My goal here is to get partial content. Can you please check on this.
_Optional<StreamProvider> sp = graphService
                    .drives(driveId)
                    .items(itemId)
                    .requestHeader("Range", "bytes=0-100")
                    .metadataFull()
                    .get()
                    .getContent();_

Also tried without .metadatafull(). Still gives whole content with 200 response

Thanks,
Pavani

**Comment by davidmoten** [comment]
Right I think I see the problem.

According to the Graph API docs https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http:

>To download a partial range of bytes from the file, your app can use the Range header as specified in RFC 2616. Note that you must append the Range header to the actual @microsoft.graph.downloadUrl URL and not to the request for /content.

So what happens is the first `.get()` gives the the information about the item including the url of the content and when we call `getContent` we want *that* call to use the Range request header. The library doesn't allow that at the moment but I'll make sure it does.

I'll have the enhancement ready shortly but in the meantime you can use custom requests.

**Comment by davidmoten** [comment]
0.1.59 is now on Maven Central. You can now do this:
```java
byte[] bytes = client
  .drives(driveId)
  .items(itemId)
  .get()
  .getContent()
  .requestHeader("Range", "bytes=0-100")
  .getBytes();
```
 Please test it and let me know how it goes.

**Comment by Pavani-Y** [comment]
Thanks David. Will check and update you.

**Comment by Pavani-Y** [comment]
Hey David. Works good! Thanks much for the quick response.

**Comment by davidmoten** [comment]
Great, glad it's working. I'll close.
