### ISSUE TITLE
Onedrive delta link, does not give top(2), but gives all changes though top is added

### ISSUE THREAD

**Issue by Pavani-Y** [davidmoten/odata-client#159]
Hi David, 
For OneDrive **delta link**, below query gives all items instead of top 3.
If this is not the right way. Please let me know how to get pagewise data for Onedrive deltalink.
graphService
        .drives("")
	.root()
	.children()
	.urlOverride(deltaLink)
	.top(3)
	.get()

Thanks,
Pavani

**Comment by davidmoten** [comment]
I suspect that the urlOverride overrides any extra setting. You could add the top query to the url string as a workaround. If you don't mind bringing back a page and truncating it then you can use .stream().limit(3). I'll look at it more closely a bit later (on holiday).

**Comment by davidmoten** [comment]
@Pavani-Y if your question is about paging in general then see https://github.com/davidmoten/odata-client#collections-and-paging

**Comment by davidmoten** [comment]
If still a problem for you reopen it.
