### ISSUE TITLE
[Documentation] Authentication with OData Service

### ISSUE THREAD

**Issue by weldnote** [davidmoten/odata-client#160]
Hi

I've found this library while needing to connect to an OData API provided by another team in my company (internal API). I've managed to generate the java classes for the `$metadata`, but I can't seem to figure out how to connect to the API itself.

I can't seem to figure out how to specify the URL for connecting to the API and how to make it so that I can pass a JWT Token in the `Authorization: Bearer` header.

I've found that I can do this... but I'm not sure about that "test()" method call, I've seen it in tests inside this repository, so it doesn't seem right.
``` final Container client =
        Container.test()
            .baseUrl("MY_CUSTOM_URL")
            .build();
 ```
And it fails anyway, since I can't really provide my access tokens. 

I've read through the documentation, source code and tests to try and figure out, but I can seem only to find examples on how to do stuff like this for connecting the MSGraph (or other MS Libraries)... 

Am I trying to do something this library is not meant to do?

I'm happy to make a PR with documentation to help out other users that want to make the same as I do.

**Comment by davidmoten** [comment]
What sort of API is it? Microsoft? Either way, an example of how to build the necessaries is in https://github.com/davidmoten/odata-client/blob/master/odata-client-microsoft-client-builder/src/main/java/com/github/davidmoten/microsoft/client/builder/MicrosoftClientBuilder.java.

**Comment by davidmoten** [comment]
I've updated my original comment. See if that helps.

**Comment by davidmoten** [comment]
BTW the `Container.test` method is for use in unit tests that make no connection to an external service. Lots of examples in https://github.com/davidmoten/odata-client/blob/edb81cf6562a9101f7fac94fe58aadf9949cd4f4/odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java (MsGraph client).

**Comment by weldnote** [comment]
Hi @davidmoten 

Thanks for the super-quick reply. I'm going to try that, the update was very useful, let me see what I can do :) Thanks again.

**Comment by davidmoten** [comment]
Beaut, will be good to get this documented. Out of interest, what product is your API?

**Comment by corrspt** [comment]
I've added a [Pull Request](https://github.com/davidmoten/odata-client/pull/161) for this situation, let me know if I can improve things. (Now with my correct account)
https://github.com/davidmoten/odata-client/pull/161

**Comment by davidmoten** [comment]
We are all sorted here I think so closing.
