### ISSUE TITLE
odata\client\TestingService.class- not returning response body for patchOrPut() method. 

### ISSUE THREAD

**Issue by Pavani-Y** [davidmoten/odata-client#173]
Hi David, 
As you resolved issue 169 to get response body for post put call, i could use it successfully. Now as i write my unit tests using below methood, i do not receive response body again. This below method in (\0.1.61\odata-client-runtime-0.1.61.jar!\com\github\davidmoten\odata\client\TestingService.class), returns only (**return new HttpResponse(response.statusCode, (byte[])null);**)
**private HttpResponse patchOrPut(String url, List<RequestHeader> requestHeaders, InputStream content, int length, HttpRequestOptions options, HttpMethod method)**  

Also method for POST - **public HttpResponse post(String url, List<RequestHeader> requestHeaders, InputStream content, int length, HttpRequestOptions options)**
fails here - String requestResourceName = (String)BuilderBase.this.requests.get(key);
                    if (requestResourceName == null) {
                        throw new RuntimeException("POST request not expected for url=" + url + ", headers=" + requestHeaders);
Not sure if this is issue with this method, it is not able to get resource name, or my code in utilizing this method. I'll tried alot but could not figure out. Please have a look if this method is good to go for same functionality to get response body in post call. This is the url i'm making post call to **/drives/{driveId}/items/{itemId}:/{fileName}:/createUploadSession**

Please do needful.
Thanks,
Pavani

**Comment by davidmoten** [comment]
No worries, I'll get that fixed. That's what i get for not writing a unit test for the last change!

**Comment by Pavani-Y** [comment]
Hi David, Can you please update on when it can be available. 
Thanks,
Pavani

**Comment by davidmoten** [comment]
Rereading your issue, I've adjusted the patch/put behaviour in the upcoming release but the POST should be doable I would have thought. See https://github.com/davidmoten/odata-client/blob/master/odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java for lots of examples on how to use TestingService.

**Comment by Pavani-Y** [comment]
Hi David, Thanks for the updates. What would be the version i need to use to get these changes?

**Comment by davidmoten** [comment]
I haven't built a new version yet. I haven't altered the post behaviour so if you have problems with post then there is something else going on. I'll need more detail on that.

**Comment by davidmoten** [comment]
I've released 0.1.62 to Maven Central with the patch/put/delete changes to TestingService.

**Comment by Pavani-Y** [comment]
```
clientBuilder()
	**.expectRequest("/drives/{driveID}/items/{itemId}:/filename.txt:/createuploadsession")**
	.withMethod(HttpMethod.POST)
	.withPayload("")
	.withRequestHeaders(RequestHeader.ODATA_VERSION, RequestHeader.CONTENT_TYPE_JSON)
	.withResponse("{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.uploadSession",
  "expirationDateTime": "2021-07-22T19:55:17.832Z",
  "nextExpectedRanges": [
    "0-"
  ],
  "uploadUrl": "..."
})
	.build();
```
This is the sample post call i'm trying to make. As i debug through TestingService.class, i understand that the path in expectRequest(with colons) to create upload session is the probelm, and the error says, **"POST request not expected for url..." .**

**Comment by davidmoten** [comment]
You can't put the json in withResponse directly. You use a classpath resource. Check link i gave you to see lots of examples.

**Comment by Pavani-Y** [comment]
Yes David, i've put the response in a path an using it here. Just to show you here, the content, i pasted here.

**Comment by davidmoten** [comment]
I've made some fixes. TestingService hadn't been used to post empty content before so I've got that working. I've also fixed a bug in `client._custom().post(...)` where `context` was being passed through as the content instead of the content. PR #175 has the changes and in particular this test now passes:

```java
@Test
    public void testDriveIssue173() {
        GraphService client = clientBuilder()
                .expectRequest("/drives/123/items/456:/filename.txt:/createuploadsession")
                .withMethod(HttpMethod.POST) //
                .withRequestHeaders(RequestHeader.ODATA_VERSION, RequestHeader.CONTENT_TYPE_JSON,
                        RequestHeader.ACCEPT_JSON)
                .withResponse("/response-drive.json") //
                .build();

        UploadSession u = client //
                ._custom() //
                .post( //
                        "https://graph.microsoft.com/v1.0/drives/123/items/456:/filename.txt:/createuploadsession", //
                        null, //
                        UploadSession.class, //
                        HttpRequestOptions.EMPTY, //
                        RequestHeader.ODATA_VERSION, //
                        RequestHeader.CONTENT_TYPE_JSON);
        assertEquals("https://blah", u.getUploadUrl().get());
    }
```

This also demos what I've been saying about using a custom request. Don't call the low-level HttpClient methods if you can help it. I'll build a release shortly and you can take it for a spin.

**Comment by davidmoten** [comment]
0.1.63 should be available on Maven Central in about 30 mins (once the release action finishes) if you'd like to try it.

**Comment by Pavani-Y** [comment]
Thanks for the update David. i'll try and update you on that.
How about the put request? the second point i mentioned. Can you please check that too.

> ```
> clientBuilder()
> 	**.expectRequest("/drives/{driveID}/items/{itemId}:/filename.txt:/createuploadsession")**
> 	.withMethod(HttpMethod.POST)
> 	.withPayload("")
> 	.withRequestHeaders(RequestHeader.ODATA_VERSION, RequestHeader.CONTENT_TYPE_JSON)
> 	.withResponse("{
>   "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.uploadSession",
>   "expirationDateTime": "2021-07-22T19:55:17.832Z",
>   "nextExpectedRanges": [
>     "0-"
>   ],
>   "uploadUrl": "..."
> })
> 	.build();
> ```
> 
> This is the sample post call i'm trying to make. As i debug through TestingService.class, i understand that the path in expectRequest(with colons) to create upload session is the probelm, and the error says, **"POST request not expected for url..." .**
> 
> Also the fix you gave, works for put content of item, through uploadurl(thats is generated through create upload session). Microsoft documentation about the api-
> https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online
> 
> But to upload content of file with url /drives/{drive-id}/items/{parent-id}:/{filename}:/content still does not work. and gives same error asd **"PUT request not expected for url..."**
> Microsoft documentation about the api-
> https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online

**Comment by davidmoten** [comment]
Release 0.1.64 with some supporting changes for the put test is being released now and will be on Maven Central in 30 mins.

I've added a unit test for your PUT case that should demonstrate what you were looking for. The test includes an example using `client._service()`  and another using `client._custom()`:

https://github.com/davidmoten/odata-client/blob/ba81decca3a5bcb96493fd671f4c44cf89d8318b/odata-client-msgraph/src/test/java/com/github/davidmoten/msgraph/GraphServiceTest.java#L1219-L1249

**Comment by davidmoten** [comment]
You'll want to use 0.1.65 because of #177.

**Comment by davidmoten** [comment]
I think this is sorted, reopen if not.
