### ISSUE TITLE
post() now does a HTTP PUT

### ISSUE THREAD

**Issue by dbaldes** [davidmoten/odata-client#177]
After upgrading from 0.1.62 to 0.1.64, post() calls on the generated API started to send a PUT request instead, resulting in a 404 in my setup.

https://github.com/davidmoten/odata-client/blob/ba81decca3a5bcb96493fd671f4c44cf89d8318b/odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/internal/ApacheHttpClientHttpService.java#L138

Is this intentional for some reason?

**Comment by davidmoten** [comment]
Sounds like a big to me, I'll fix shortly.

**Comment by davidmoten** [comment]
Fix will be in 0.1.65 which should be on Maven Central in 30mins, let me know if works!

**Comment by dbaldes** [comment]
Works for me now, thanks!

**Comment by davidmoten** [comment]
Excellent, thanks for the report!
