### ISSUE TITLE
Paging via @odata.nextLink

### ISSUE THREAD

**Issue by abhishekthetechguy** [davidmoten/odata-client#18]
Hello David 

Thanks for all your efforts. As per your changes in [https://github.com/davidmoten/odata-client/#getting-a-collection-from-a-link](url), we can now do explicit paging and retrieve next page via Odata.nextLink property. 

From my understanding, the Odata.nextLink can be retrieved as below
`OdataClientFactory
.request()
.users()
.top(n)
.get()
.nextLink()`

While the current page with usage of top() can be retrieved as below
`OdataClientFactory.request().users().top(long n).get().currentPage()`

By any chance can we get the nextLink as part of the currentPage data itself ? For example when using top in MS Graph api, we get the below output 

`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/users?$top=3&$skiptoken=X%2744537074020001000000253A616268697368656B30324064706F3336356261722E6F6E6D6963726F736F66742E636F6D29557365725F64623435656264662D613139662D343834342D386438652D653535306531396265356163B900000000000000000000%27",
    "value": [
        {
            "businessPhones": [
                "4251001000"
            ],
}
`

As you can see, here the nextLink is available as part of the retrieved page content itself. Do we have a similar facility in the Odata-client ? Bascially, I would like to have the nextLink returned as par of my currentPage itself. I need to return this information to a client which will then decide how to use the nextLink.

**Comment by davidmoten** [comment]
This doesn't make sense to me. When you call `client.users().get()`, the `currentPage()` method gives you the list of items in the current page and `nextLink()` is the value of `@odata.nextLink` in the json for that page.

So do this:

```java
CollectionPage<User> page = client.users().get();
List<User> users = page.currentPage();
String nextLink = page.nextLink();
```
Incidentally can you stop including `OdataClientFactory.request()` in these issues because it is your api only and would confuse other readers. You do realize you only need to create the client once don't you? It will handle token refreshes over time under the covers.

**Comment by abhishekthetechguy** [comment]
Hi David 

Thanks for replying. Will make sure to not include my api reference going further. 
I understand the example code that you have provided and fully agree that we can do this.

The reason I was asking about being able to get the `nextLink` is because when implementing explicit paging, I intend to send the data to client page wise. So if the `currentPage` output will have the `nextLink` for the next page in it as well, the client can then simply extract the `nextLink` information on their side and then ask for the next page using that nextLink which would again return the page content and the `nextLink` for the next page. In this way we will be able to chain the page requests.

Other way would be to of course have the client ask the information about the `nextLink` explicitly which I am willing to avoid if possible. 


> This doesn't make sense to me. When you call client.users().get(), the currentPage() method gives you the list of items in the current page and nextLink() is the value of @odata.nextLink in the json for that page.

On a different note, unfortunately, I have not been able to see the `nextLink` information in the json when I return the collectionPage<User> via my api call. While debugging I can see that we have the information available in the collection but then when I see the final output( on the web browser for example), it is not visible there. I understand this is an issue on my side as we are loosing this information while sending back the response. Just sharing with you in hope of getting some feedback if possible.

**Comment by davidmoten** [comment]
Ah wait so you really just want to give the json from the Graph service straight on to you client?

**Comment by davidmoten** [comment]
If you try and serialize `List<User>` it definitely won't have `@odata.nextLink` in it. You would have to serialize `List<User>` to json and insert the `@odata.nextLink` field into that json to give to your client.

**Comment by abhishekthetechguy** [comment]
> Ah wait so you really just want to give the json from the Graph service straight on to you client?

Yes :) . We are actually building a service that will be called by multiple clients. Apologies if I wasn't clear enough earlier


> If you try and serialize List<User> it definitely won't have @odata.nextLink in it. You would have to serialize List<User> to json and insert the @odata.nextLink field into that json to give to your client

Yes, this is something I thought. I don't know how to do it at the moment( courtesy my CPP background as a dev) but I hope I will be able to figure it out. Just want to understand why does the serialization of List<User> drop the @odata.nextLink field in the first  place? Apologies for asking if its something obvious but I haven't been able to figure this out yet

**Comment by davidmoten** [comment]
The api returns something like below for the collection get. When you serialize `List<Contact>` you just get the `value` field below.

```json

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('48d31887-5fad-4d73-a9f5-3c356e68a038')/contacts",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/contacts?$skip=10",
    "value": [
        {
            "@odata.etag": "W/\"EQAAABYAAAAiIsqMbYjsT5e/T7KzowPTAAAYc8Bf\"",
            "id": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OABGAAAAAAAiQ8W967B7TKBjgx9rVEURBwAiIsqMbYjsT5e-T7KzowPTAAAAAAEOAAAiIsqMbYjsT5e-T7KzowPTAAAYbuK-AAA=",
            "createdDateTime": "2017-09-04T15:54:01Z",
            "lastModifiedDateTime": "2017-09-04T15:54:02Z",
            "changeKey": "EQAAABYAAAAiIsqMbYjsT5e/T7KzowPTAAAYc8Bf",
            "categories": [],
            "parentFolderId": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAEOAAA=",
            "birthday": null,
            "fileAs": "",
            "displayName": "Alex Wilber",
            "givenName": "Alex",
            "initials": null,
            "middleName": null,
            "nickName": null,
            "surname": "Wilber",
            "title": null,
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": null,
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": null,
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "",
            "children": [],
            "emailAddresses": [
                {
                    "name": "Alex@FineArtSchool.net",
                    "address": "Alex@FineArtSchool.net"
                }
            ],
            "homeAddress": {},
            "businessAddress": {},
            "otherAddress": {}
        },
        {
            "@odata.etag": "W/\"EQAAABYAAAAiIsqMbYjsT5e/T7KzowPTAAAYc8Be\"",
            "id": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OABGAAAAAAAiQ8W967B7TKBjgx9rVEURBwAiIsqMbYjsT5e-T7KzowPTAAAAAAEOAAAiIsqMbYjsT5e-T7KzowPTAAAYbuK_AAA=",
            "createdDateTime": "2017-09-04T15:54:01Z",
            "lastModifiedDateTime": "2017-09-04T15:54:01Z",
            "changeKey": "EQAAABYAAAAiIsqMbYjsT5e/T7KzowPTAAAYc8Be",
            "categories": [],
            "parentFolderId": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAEOAAA=",
            "birthday": null,
            "fileAs": "",
            "displayName": "Angel Garcia",
            "givenName": "Angel",
            "initials": null,
            "middleName": null,
            "nickName": null,
            "surname": "Garcia",
            "title": null,
            "yomiGivenName": null,
            "yomiSurname": null,
            "yomiCompanyName": null,
            "generation": null,
            "imAddresses": [],
            "jobTitle": null,
            "companyName": null,
            "department": null,
            "officeLocation": null,
            "profession": null,
            "businessHomePage": null,
            "assistantName": null,
            "manager": null,
            "homePhones": [],
            "mobilePhone": "(302) 555-0104",
            "businessPhones": [],
            "spouseName": null,
            "personalNotes": "",
            "children": [],
            "emailAddresses": [],
            "homeAddress": {},
            "businessAddress": {},
            "otherAddress": {}
        }
    ]
}
```

**Comment by abhishekthetechguy** [comment]
I see ! So that is how serialization is implemented for odata-client? Or its some kind of generic behavior?

**Comment by davidmoten** [comment]
That json is raw json from the Graph API.

The library is designed to throw away json for garbage collection as soon as it is unmarshalled to an object or list of objects. It's memory efficient. I'll ponder how you can do what you want.

**Comment by davidmoten** [comment]
I'll make an example that will do what you want (build the json to return to your client).

**Comment by abhishekthetechguy** [comment]
Thanks David, for the prompt response. Highly appreciate your help

**Comment by davidmoten** [comment]
Ok here you go. I've tested this and works.

You need this class (call it what you want):
```java
public final class MyPage<T> {
    @JsonProperty(value="@odata.nextLink")
    final String nextLink;
    @JsonProperty(value="value")
    final List<T> value;
        
    MyPage( List<T> value, Optional<String> nextLink) {
        this.nextLink = nextLink.orElse(null);
        this.value = value;
    }
}
```
then
```java
CollectionPage<User> page = client.users().get();
MyPage<User> p = new MyPage<>(page.currentPage(), page.nextLink());
String json = Serializer.INSTANCE.serialize(p);
```

**Comment by abhishekthetechguy** [comment]
Yes at the moment we need only this part. Will confirm to you once I get this working. 
Thanks again and have a good evening !

**Comment by davidmoten** [comment]
Righto, I've made it easy for you. I've released 0.1.17 to Maven Central in which `CollectionPage` has a `toJsonMinimal()` method. Try that out.

```java
String json = client.users().get().toJsonMinimal();
```

**Comment by davidmoten** [comment]
@abhishekthetechguy did you give the new method a try?

**Comment by abhishekthetechguy** [comment]
HI David

Sorry about the late reply. Been a little busy. Actually what I was able to use the `MyPage`  class itself. Serializing that class gives us data that is more aligned in json form and is better to visualise on the client( web browser for example). 

So after creating the `MyPage` class object
`MyPage<User> p = new MyPage<>(page.currentPage(), page.nextLink());`

I just return the created page as below 
`return Flux.just(customPage);`
 
With the string output, the output isn't properly formatted in the sense that everything appears in one single line. I haven't yet been able to test the `toJsonMinimal()` method. Will do it asap and let you know. 

Just a suggestion from my side. I think in my view, it may be worth adding  a similar method which return us the `MyPage` obect instead of string as it keeps the output better formatted and easier to read. Thanks for your time. I will test version `0.1.17` and confirm the effect soon

**Comment by davidmoten** [comment]
Glad you have it working. I don't think it's worthwhile putting a pretty formatted option on `toJsonMinimal`(nor exposing the `MyPage` object to the public API. That's a debugging/presentation concern. If anyone wants that much control then they can use the `MyPage` approach as you have and their own style of JSON marshaller.

**Comment by davidmoten** [comment]
It just struck me that it might be possible to make annotate the methods on `CollectionPage` itself so that it serializes to JSON. I'll look at that.

**Comment by davidmoten** [comment]
Yep that works, and I added methods to Serializer to pretty print JSON so you can do:

```java
CollectionPage<User> users = client.users().get();
String json = Serializer.INSTANCE.serializePrettyPrint(users);
``` 
You get pretty printed json like this:
```json
{
  "@odata.nextLink" : "https://graph.microsoft.com/v1.0/me/contacts?$skip=10",
  "value" : [ {
    "parentFolderId" : "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAEOAAA=",
    "fileAs" : "",
    "displayName" : "Alex Wilber",
    "givenName" : "Alex",
    "surname" : "Wilber",
    "emailAddresses" : [ {
      "name" : "Alex@FineArtSchool.net",
      "address" : "Alex@FineArtSchool.net"
    } ],
...
```
If you think that might be useful I'll release it.

**Comment by abhishekthetechguy** [comment]
Hi David

Yes, I believe it will be useful. Just one point , is the value of `odata.nextLink` correct here ? I mean it looks like as if it has been truncated. Generally the value for it is a quite big URL , something like this below
`@odata.nxtLink : https://graph.microsoft.com/v1.0/users?$top=3&$skiptoken=X%27445370740200010000002D3A6E656572616A62616E73616C406461746170726F746563746F7231392E6F6E6D6963726F736F66742E636F6D29557365725F31303838356562332D633861662D343738352D623237642D316536363538636161386139B900000000000000000000%27"`

**Comment by davidmoten** [comment]
The example is actually from Contacts and uses skip not skipToken, that's why it's short.

**Comment by davidmoten** [comment]
Changes above in 0.1.19 which is on Maven Central now.

**Comment by abhishekthetechguy** [comment]
Thanks David. Shall use this and confirm

**Comment by davidmoten** [comment]
See also discussion in #22. I'll close this now because I think it's been addressed. Reopen if you need to.

**Comment by abhishekthetechguy** [comment]
Thanks David. I tested it just a while back 0.1.19 and it is working fine.

**Comment by davidmoten** [comment]
@abhishekthetechguy excellent. We are up to 0.1.22 now. I'm quite active on this project at the moment so if you want to hear of new releases click the Watch Releases button.

**Comment by abhishekthetechguy** [comment]
Glad to hear it ! Will surely watch the releases going further. Also, I have just opened another issue #29. Please check it once when you can manage some time.
