### ISSUE TITLE
Listing users and sub-groups inside a group separately

### ISSUE THREAD

**Issue by shubhamarora97** [davidmoten/odata-client#19]
Hi David,

Thanks a lot for the Odata-client  library and I appreciate that odata client library is a very  powerful tool.
I had  use cases where I wanted to list all the users in a group and sub-group inside a group separately(On going through Graph documentation, I could see that I can create only Security group inside security group).

I have gone through Odata library and saw that I can use members() for group  but it is listing groups as well as users also.

I can differentiate users and sub-groups inside a group by  @odata.type property.
For group, it would be  "@odata.type": "#microsoft.graph.group",
For user, it would be   "@odata.type": "#microsoft.graph.user"

I tried to filter by this property but I think it is an limitation from Graph API that we cannot filter using @odata.type property.
 Can you please help me with how I can  differentiate the members in a group by @odata.type property using Odata-client

**Comment by davidmoten** [comment]
A bit more googling would have got you there. There is an `isOf` operator you can use in a filter:

```
GET https://graph.microsoft.com/beta/directoryObjects/delta?$filter=isOf('Microsoft.Graph.User')+or+isOf('Microsoft.Graph.Group')
```
From https://docs.microsoft.com/en-us/graph/api/directoryobject-delta?view=graph-rest-beta&tabs=http#request-3

**Comment by davidmoten** [comment]
Ah I forgot there is another way of doing this (I added support for this a couple of weeks ago for another user):

Try:

```java
CollectionPage<User> page = client.users().memberOf().filter(User.class).get();
```

**Comment by shubhamarora97** [comment]
> 
> 
> A bit more googling would have got you there. There is an `isOf` operator you can use in a filter:
> 
> ```
> GET https://graph.microsoft.com/beta/directoryObjects/delta?$filter=isOf('Microsoft.Graph.User')+or+isOf('Microsoft.Graph.Group')
> ```
> 
> From https://docs.microsoft.com/en-us/graph/api/directoryobject-delta?view=graph-rest-beta&tabs=http#request-3

I was referring to docs for Microsoft Graph API 1.0.
I did not want to use the beta version for Microsoft Graph API.

**Comment by shubhamarora97** [comment]
> 
> 
> Ah I forgot there is another way of doing this (I added support for this a couple of weeks ago for another user):
> 
> Try:
> 
> ```java
> CollectionPage<User> page = client.users().memberOf().filter(User.class).get();
> ```

I tried this example and it worked for me.
CollectionPage<User> page = client.users().members().filter(User.class).get();

Now, I am able to list sub-groups and users in a group separately.
Thanks a lot for the response and have a good day.

**Comment by davidmoten** [comment]
What version are you using?

When I try `client.users()` there is no `.members()` method.

**Comment by davidmoten** [comment]
Ah you mean `client.groups().members()`?

**Comment by shubhamarora97** [comment]
> 
> 
> Ah you mean `client.groups().members()`?

Yes.

> 
> 
> > Ah I forgot there is another way of doing this (I added support for this a couple of weeks ago for another user):
> > Try:
> > ```java
> > CollectionPage<User> page = client.users().memberOf().filter(User.class).get();
> > ```
> 
> I tried this example and it worked for me.
> CollectionPage page = client.groups().members().filter(User.class).get();
> 
> Now, I am able to list sub-groups and users in a group separately.
> Thanks a lot for the response and have a good day.

**Comment by davidmoten** [comment]
Ripper, glad you're sorted.

**Comment by shubhamarora97** [comment]
> 
> 
> Ah you mean `client.groups().members()`?

Yes, groups().members().
It was a typo.

**Comment by shubhamarora97** [comment]
> 
> 
> > Ah you mean `client.groups().members()`?
> 
> Yes, groups().members().
> It was a typo.

Thanks a lot.

**Comment by shubhamarora97** [comment]
One last thing, we can filter groups with odata-client on the basis of group-type which can be unified or null(i.e- Security and Office 365 group)
In Graph API 1.0 we cannot filter with group-type property.

**Comment by davidmoten** [comment]
>One last thing, we can filter groups with odata-client on the basis of group-type which can be unified or null(i.e- Security and Office 365 group)
In Graph API 1.0 we cannot filter with group-type property.

So groupType is a collection itself in a group so you'd need to look for some `contains` operator in a filter. If you want all users in groups of a certain group-type or group-types then I doubt you'd be able to do it in one call (OData does not give you full sql-like join control). Just return the appropriate groups then on each group return the users. Are there so many groups returned that you can't filter client side? If you are concerned with bringing back lots of data in these calls then use `.select` and `.metadataNone()`.

**Comment by davidmoten** [comment]
Client side filtering using streams and `select` to reduce data downloaded:

```java
List<User> users = client //
    .groups() //
    .select("id,groupTypes") //
    .stream() //
    .filter(g -> {
        Set<String> set = g.getGroupTypes().toSet();
        return set.contains("Unified") || set.contains("Blah");
    }) //
    .flatMap(g -> g.getMembers().filter(User.class).stream()) //
    .collect(Collectors.toList());
```

**Comment by shubhamarora97** [comment]
> 
> 
> > One last thing, we can filter groups with odata-client on the basis of group-type which can be unified or null(i.e- Security and Office 365 group)
> > In Graph API 1.0 we cannot filter with group-type property.
> 
> So groupType is a collection itself in a group so you'd need to look for some `contains` operator in a filter. If you want all users in groups of a certain group-type or group-types then I doubt you'd be able to do it in one call (OData does not give you full sql-like join control). Just return the appropriate groups then on each group return the users. Are there so many groups returned that you can't filter client side? If you are concerned with bringing back lots of data in these calls then use `.select` and `.metadataNone()`.

Thanks for the information.
