### ISSUE TITLE
HttpPatch Delta<T> parameter is always Null

### ISSUE THREAD

**Issue by msaifi** [davidmoten/odata-client#196]
Hi,

I wrote an oData4 enabled API  in Asp.Net core 5. The API exposes HttpGet, HttpPost, HttpPut, HttpPatch, and HttpDelete.
I tested the API with postman and all works fine. Inclusively, HttpPatch which I am having problem when trying it with Microsoft.oData.Client.

On the client side, I wrote a console application that uses Microsoft.oData.Client. The problem is on the API side. I set a breakpoint on HttpPatch Action, and Delta<T> is always null when accessed through "Microsoft.oData.Client". I tested HttpPatch with "Simple.OData.Client" and postman and all worked as expected.

The client code is:

`    public class MyContainer : DataServiceContext`
    `{`
       ` public DataServiceQuery<SinergiaView> SinergiaViewSet { get; }`
       `public MyContainer(Uri serviceRoot) : base(serviceRoot)`
        `{`
         `   SinergiaViewSet = base.CreateQuery<SinergiaView>("SinergiaViewSet");`
        `}`
        `public void AddSinergiaView(SinergiaView entity)`
        `{`
         `   base.AddObject("SinergiaViewSet", entity);`
        `}`
    `}`
`static async Task Main(string[] args)`
`{`
           `var mylocalContext = new MyContainer(new Uri("https://localhost:44666/odata"));`
            `var myEntity = mylocalContext.SinergiaViewSet.Where(p => p.PK == 1).FirstOrDefault();`
            `myEntity.TimeStamp = 9;`
            `mylocalContext.UpdateObject(myEntity);`
            `await mylocalContext.SaveChangesAsync();`
`}`

I have been trying to workaround for more than one week, but no success. I gave up, and I am asking for any one to help.
I appreciate a lot any contribution to this issue

**Comment by davidmoten** [comment]
Hi, this  doesn't appear to be related to this project. Ask on StackOverflow.
