### ISSUE TITLE
Nulls in response

### ISSUE THREAD

**Issue by RajatNair** [davidmoten/odata-client#22]
Hi David, 

In the older version of library (v0.1.12), the response from Odata client did not contain `nulls`, which MS Graph SDK notoriously did. It was something like this for User endpoint - 
```JSON
{
  "businessPhones": [],
  "displayName": "John Martin",
  "givenName": "John",
  "surname": "Martin",
  "userPrincipalName": "john.martin@19.onmicrosoft.com",
  "id": "8fce020a-ff47-45b1-a533-d2cf7e954ebd"
}
```

But with v0.1.17, I see this - 
```JSON
{
  "@odata.type": null,
  "accountEnabled": null,
  "ageGroup": null,
  "assignedLicenses": null,
  "assignedPlans": null,
  "businessPhones": [],
  "city": null,
  "companyName": null,
  "consentProvidedForMinor": null,
  "country": null,
  "creationType": null,
  "department": null,
  "displayName": "John Martin",
  "employeeId": null,
  "externalUserState": null,
  "externalUserStateChangeDateTime": null,
  "faxNumber": null,
  "givenName": "John",
  "identities": null,
  "imAddresses": null,
  "isResourceAccount": null,
  "jobTitle": null,
  "lastPasswordChangeDateTime": null,
  "legalAgeGroupClassification": null,
  "licenseAssignmentStates": null,
  "mail": null,
  "mailNickname": null,
  "mobilePhone": null,
  "onPremisesDistinguishedName": null,
  "onPremisesExtensionAttributes": null,
  "onPremisesImmutableId": null,
  "onPremisesLastSyncDateTime": null,
  "onPremisesProvisioningErrors": null,
  "onPremisesSecurityIdentifier": null,
  "onPremisesSyncEnabled": null,
  "onPremisesDomainName": null,
  "onPremisesSamAccountName": null,
  "onPremisesUserPrincipalName": null,
  "otherMails": null,
  "passwordPolicies": null,
  "passwordProfile": null,
  "officeLocation": null,
  "postalCode": null,
  "preferredLanguage": null,
  "provisionedPlans": null,
  "proxyAddresses": null,
  "showInAddressList": null,
  "signInSessionsValidFromDateTime": null,
  "state": null,
  "streetAddress": null,
  "surname": "Martin",
  "usageLocation": null,
  "userPrincipalName": "john.martin@19.onmicrosoft.com",
  "userType": null,
  "mailboxSettings": null,
  "deviceEnrollmentLimit": null,
  "aboutMe": null,
  "birthday": null,
  "hireDate": null,
  "interests": null,
  "mySite": null,
  "pastProjects": null,
  "preferredName": null,
  "responsibilities": null,
  "schools": null,
  "skills": null,
  "id": "8fce020a-ff47-45b1-a533-d2cf7e954ebd",
  "deletedDateTime": null,
  "assignedLicenses@nextLink": null,
  "assignedPlans@nextLink": null,
  "businessPhones@nextLink": null,
  "identities@nextLink": null,
  "imAddresses@nextLink": null,
  "licenseAssignmentStates@nextLink": null,
  "onPremisesProvisioningErrors@nextLink": null,
  "otherMails@nextLink": null,
  "provisionedPlans@nextLink": null,
  "proxyAddresses@nextLink": null,
  "interests@nextLink": null,
  "pastProjects@nextLink": null,
  "responsibilities@nextLink": null,
  "schools@nextLink": null,
  "skills@nextLink": null
}
```

Is this a defect or was this design change intentional?

**Comment by davidmoten** [comment]
definitely a defect, introduced by recent fix. I'll have a look, thanks!

**Comment by davidmoten** [comment]
Ah wait, this is not the response from the graph service but what happens when you serialize a `User` object? How do you serialize it? In a recent fix I did remove an annotation from entity objects so that you will now have to instruct the serializer to exclude nulls. `Serializer.INSTANCE` does this by default:
```java
User user = User.builderUser().id("12345").build();
System.out.println(Serializer.INSTANCE.serialize(user));
```
output:
```
{"@odata.type":"microsoft.graph.user","id":"12345"}
```

**Comment by RajatNair** [comment]
> How do you serialize it?

Serializing it using - 
```Java
ServerResponse.ok().contentType(MediaType.APPLICATION_STREAM_JSON).body(this.service.listUsers(), User.class)
```
where listUsers return `Flux<Stream<odata.msgraph.client.entity.User>>`

The above sample I had posted using v0.1.12 and v0.1.17 was using the same code.

**Comment by davidmoten** [comment]
Entity objects used to have a class level annotation `@JsonInclude(Include.NON_NULL)` which was friendly for your use case. I removed that annotation because it was breaking a scenario where we do want to serialize some or all nulls (updating fields to null in a patch).

So if you are serializing it using Spring Webflux then just configure Webflux to exclude nulls. I found lots of information when I googled "webflux customize json serialization"

**Comment by davidmoten** [comment]
I'll have a look at returning the class level annotation but I doubt that I can override it (which I need to do). So no promises!

**Comment by davidmoten** [comment]
Ah yes, I can override the class level annotation. So don't worry about customizing your serializer, I'll change all generated objects to have `@JsonInclude(Include.NON_NULL)` again.

**Comment by davidmoten** [comment]
Trying to do this I think I've encountered Jackson bugs in relation to setting the AnnotationInspector. I've got a workaround but feels like I've opened a Pandora's box of more detective work!

**Comment by davidmoten** [comment]
The change you want is in release 0.1.20 on Maven Central now.

**Comment by davidmoten** [comment]
By the way we can probably get the default serialization to suppress including empty arrays as well. I'll have to make sure it doesn't have any nasty side-effects though.

**Comment by davidmoten** [comment]
I think this is done so closing. Reopen if you need to.

**Comment by RajatNair** [comment]
> I think this is done so closing. Reopen if you need to.

Validated the fix, it's working as expected. Thanks.

> By the way we can probably get the default serialization to suppress including empty arrays as well. I'll have to make sure it doesn't have any nasty side-effects though.

Can you give me some pointers? Which Jackson class should I be extending?

**Comment by davidmoten** [comment]
> Validated the fix, it's working as expected. Thanks.

Good to hear.

>>By the way we can probably get the default serialization to suppress including empty arrays as well. I'll have to make sure it doesn't have any nasty side-effects though.

>Can you give me some pointers? Which Jackson class should I be extending?

I would just replace the `@JsonInclude(Include.NON_NULL)` annotation at the top of all entities, complex types, collectionPage with `@JsonInclude(Include.NON_EMPTY)`.
