### ISSUE TITLE
Support "Evolvable Enumerations" with a default value

### ISSUE THREAD

**Issue by ZMiller01** [davidmoten/odata-client#298]
https://learn.microsoft.com/en-us/graph/best-practices-concept#handling-future-members-in-evolvable-enumerations

MS Graph enums that may have future values added to them will contain a "sentinel" value of `unknownFutureValue`. A special request header must be added to get the MS APIs to return future values, I suspect that Jackson will fail to deserialize them to the generated Java enums. Jackson uses the annotation `@JsonEnumDefaultValue` along with the object mapper option "READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE" to support deserializing to that value.

I would propose that the code generator add `@JsonEnumDefaultValue` when the source string value is equal to `unknownFutureValue`.

**Comment by davidmoten** [comment]
ok thanks, I'll have a ponder

**Comment by davidmoten** [comment]
So your suggestion seems good as protection in that circumstance, I'll knock up a PR for your review.

**Comment by davidmoten** [comment]
Hi, please review PR #299

**Comment by davidmoten** [comment]
#299 has been merged and 0.1.83 built and is on Maven Central with support for this idea. 

Thanks for raising this @ZMiller01.

**Comment by ZMiller01** [comment]
Thank you for the quick turnaround!
