### ISSUE TITLE
Paging example

### ISSUE THREAD

**Issue by RajatNair** [davidmoten/odata-client#3]
Hi David,

Thanks for this excellent library. I couldn't agree more to issues mentioned [here](https://github.com/davidmoten/odata-client/wiki/Microsoft-msgraph-sdk-java-problems-addressed-by-odata-client) 

Can you share an example of how we can page data using odata client? Does it internally use `skiptoken`? Would it be possible to set the pagesize?

**Comment by davidmoten** [comment]
Hi @RajatNair, thanks. I hope the library can be useful to people. 

Here are simple examples:

Use `stream`:
```java
String mailbox = "me";
client
    .users(mailbox) 
    .mailFolders("Inbox") 
    .messages() 
    .stream() 
    .limit(100)
    .map(x -> x.getSubject().orElse("")) 
    .forEach(System.out::println);
```
Use an iterator:
```java
CollectionPage<Message> messages = client
    .users(mailbox) 
    .mailFolders("Inbox") 
    .messages()
    .get(); 
for (Message m: messages) {
    System.out.println(m.getSubject().orElse(""));
}
```

The `.stream()` or `.iterator()` methods handle paging for you. Paging is determined server-side and the page size itself is controlled there. I'm not aware of being able to change the page size beyond use of `$top` which would only limit the size of the final page. Under the covers when a page of json comes back it includes an `@odata.nextLink` item that is the link for the next page (if there is one). Real-life interactions with the Graph api that I have seen have used the `skip` parameter and I understand from the Graph documentation that some parts of the api use `skiptoken`. The library doesn't really care, it just calls the nextLink.

**Comment by davidmoten** [comment]
BTW you can also call the `currentPage` and `nextPage` methods on `CollectionPage` to have explicit control of paging.

**Comment by davidmoten** [comment]
I should probably add the information I've just given you to a Paging section in the README.md.

**Comment by RajatNair** [comment]
>  The library doesn't really care, it just calls the nextLink.

Based on this [document](https://docs.microsoft.com/en-us/graph/paging), the  `@odata.nextLink` contains the skiptoken/skip parameter. So we are on the right track using MS recommended way of doing paging. Hope that insulates us from breaking changes.

> I'm not aware of being able to change the page size beyond use of $top which would only limit the size of the final page.

Could you explain further?

> you can also call the currentPage and nextPage methods on CollectionPage to have explicit control of paging.

I was trying to implement custom paging for a SPA client, where the UI decides how many rows of data it wants to display. Using `top()`, I could limit the number of rows fetched from Graph and the `currentPage()` and `nextPage()` helps iterate through the collections. But `currentPage()`/`nextPage()`  are not available on stream(). How would we perform paging using streams?

![image](https://user-images.githubusercontent.com/3319907/83794842-33b84c00-a6bc-11ea-92cd-45eef4a3cb39.png)


Another issue is that the `odata-client` library is used by a REST service, so we are not maintaining any state on server side and are expecting the client to send the `@odata.nextLink`. Not sure how we can set `@odata.nextLink` to the library to call the `nextPage()` method.

**Comment by davidmoten** [comment]
Forget about $top. I meant if the page size is 10 and you set $top=35 then you'll get 3 pages of 10 and one page of 5. i.e. it improves efficiency by reducing the size of the final page (only).

`currentPage` and `nextPage` are for manually calling each page. The whole point of the `stream` method is paging happens in the background. You can see how `stream` does its paging in [Paged.java](https://github.com/davidmoten/odata-client/blob/master/odata-client-runtime/src/main/java/com/github/davidmoten/odata/client/Paged.java).

Remember you don't control page size with msgraph. They don't let you and that's quite understandable. You have a notion of a page in your UI which doesn't have to have the same size as the page in the msgraph requests. 

What you need to do is convert your `Stream<User>` into a `Stream<List<User>>` where the lists in the stream are the size of your UI page. To do this I looked up "java stream buffer to lists" in google and you see how to do it on https://stackoverflow.com/questions/47842871/buffer-operator-on-java-8-streams. It's very annoying that java.util.stream.Stream doesn't already have that operator built in, that's one of the reasons I made [kool](https://github.com/davidmoten/kool).

**Comment by davidmoten** [comment]
> we are not maintaining any state on server side and are expecting the client to send the @odata.nextLink

#17 provides you with what you need. Released in 0.1.16 to Maven Central just now.

**Comment by davidmoten** [comment]
See updated [Collections and paging](https://github.com/davidmoten/odata-client/blob/master/README.md#collections-and-paging) section in the README.md for new features about page size control including utility functions that I mentioned above but also enabling the passing of an HTTP request header with page size preference.

**Comment by RajatNair** [comment]
That was some fast turnaround! 👍 

The changes in the last few weeks related to paging has answered my query. Marking the issue as closed.
