### ISSUE TITLE
Hit java reserved identifier 'package'

### ISSUE THREAD

**Issue by sudechun** [davidmoten/odata-client#347]
target/generated-sources/java/microso
ft/dynamics/crm/entity/request/PluginpackageRequest.java:[106,33] <identifier> e
xpected
[ERROR]

**Comment by davidmoten** [comment]
Got more details?

**Comment by sudechun** [comment]
public FileattachmentRequest package() {
        return new FileattachmentRequest(contextPath.addSegment("Package"), Optional.empty());
    }

**Comment by davidmoten** [comment]
Righto, that's fixed in release [0.1.87](https://github.com/davidmoten/odata-client/releases/tag/0.1.87) which I've pushed to Maven Central. Should be available there for download within 30 mins. Give that a shot and let me know how it went.

**Comment by davidmoten** [comment]
Available for download on Maven Central now
