### ISSUE TITLE
Issue with the /delta query

### ISSUE THREAD

**Issue by madanbisht** [davidmoten/odata-client#37]
Hi David,
    Can you please help  us here, we are getting 'user' information successfully via `'users().stream();'` but when we use delta, to get incremental data its reporting exception.

**Request:**
```
                     users()
                    .delta()
                    .stream();
```
**Response: Exception**
```
{
    "timestamp": "2020-08-13T09:35:43.017+00:00",
    "path": "/v1/users",
    "status": "METHOD_NOT_ALLOWED",
    "error": "Method Not Allowed",
    "message": "responseCode=405 from url=https://graph.microsoft.com/v1.0/users/delta, expectedResponseCode in [200, 200], message=\n{\r\n  \"error\": {\r\n    \"code\": \"Request_BadRequest\",\r\n    \"message\": \"Specified HTTP method is not allowed for the request target.\",\r\n    \"innerError\": {\r\n      \"date\": \"2020-08-13T09:35:42\",\r\n      \"request-id\": \"23b657e4-634a-4679-b95f-b98486d2d971\"\r\n    }\r\n  }\r\n}",
    "requestId": "952a8c7e-1",
    "statusCode": 405
}
```

**Comment by madanbisht** [comment]
We also tried the same with mailMessages, without delta its successfully returning mails but when we use `delta` its reporging exception:

```
                    .users("bisht@backuprecovery1.onmicrosoft.com")
                    .mailFolders().id("inbox")
                    .messages()
                    .delta()
                    .get();
```
Response: Exception
```
{
    "timestamp": "2020-08-14T06:53:54.377+00:00",
    "path": "/v1/messages",
    "status": "METHOD_NOT_ALLOWED",
    "error": "Method Not Allowed",
    "message": "responseCode=405 from url=https://graph.microsoft.com/v1.0/users/bisht%40backuprecovery1.onmicrosoft.com/mailFolders/inbox/messages/delta, expectedResponseCode in [200, 200], message=\n{\r\n  \"error\": {\r\n    \"code\": \"ErrorInvalidRequest\",\r\n    \"message\": \"The OData request is not supported.\",\r\n    \"innerError\": {\r\n      \"date\": \"2020-08-14T06:52:32\",\r\n      \"request-id\": \"f2f1cd3f-8faa-4eb8-81f3-42e6398292ce\"\r\n    }\r\n  }\r\n}",
    "requestId": "c53e858b-2",
    "statusCode": 405
}

```

**Comment by davidmoten** [comment]
Thanks for the report. I'll have a look.

**Comment by davidmoten** [comment]
I've had a look and as the error message suggests odata-client-msgraph is using Http POST whereas odata Functions should use GET (https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31359010). I'll fix now.

**Comment by davidmoten** [comment]
So the fix works using GraphExplorer but it appears there is special handling for delta streams in the OData specification that I haven't considered yet so I'll look at that too (http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Requesting_Changes_2).

**Comment by madanbisht** [comment]
Thanks David, appreciate your quick response.

**Comment by davidmoten** [comment]
I've fixed the HTTP method for Functions and added delta support in 0.1.30 which is on Maven Central now. See https://github.com/davidmoten/odata-client#delta-collections for usage.

Give it a shot, see if it works for you, thanks.

**Comment by madanbisht** [comment]
Hi David,
   We have validated and its working as expected.

Thanks a lot for your understanding and immediate resolution.
