### ISSUE TITLE
support Microsoft Analytics for DevOps OData services

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/odata-client#41]
This discussion was raised in #39 and has been moved here (#39 has been fixed).

**Comment by rmkellogg** [comment]
[Azure-Boards-Metadata.zip](https://github.com/davidmoten/odata-client/files/5123612/Azure-Boards-Metadata.zip)
In regards to the custom fields I created at the organization level, the field definition is present.  There were two projects created under the same organization.  One has the custom field and the other does not.  Assume this is some bugs on the server side.  Metadata files attached to demonstrate problem.  I doubt any changes needed in your client side code.

**Comment by davidmoten** [comment]
Base support for services in release 0.1.32
