### ISSUE TITLE
odata-client-msgraph: Support for legacy extended properties

### ISSUE THREAD

**Issue by codemasterover9000** [davidmoten/odata-client#426]
Hi Dave,

We are currently using the official MS graph client and are looking for something more lightweight in terms of dependencies. We came across your project which seems a perfect match.

We have one issue though we depend on (legacy) [extended properties](https://learn.microsoft.com/en-us/graph/api/resources/extended-properties-overview?view=graph-rest-1.0) for our application. Which originated as a SOAP based Exchange integration through EWS. We use it to to attach application specific metadata to events. Which is also used in queries.

Specifically [singleValueLegacyExtendedProperty](https://learn.microsoft.com/en-us/graph/api/resources/singlevaluelegacyextendedproperty?view=graph-rest-1.0). The class is in the library but does not seem to be used.

Do you have any plans to support this?

**Comment by davidmoten** [comment]
Interesting. I'll have a look.

**Comment by davidmoten** [comment]
As a workaround to create that property you do this with a [custom command](https://github.com/davidmoten/odata-client?tab=readme-ov-file#custom-requests):

```
PATCH https://graph.microsoft.com/v1.0/me/messages/AAMkAGE1M2_bs88AACHsLqWAAA=
Content-Type: application/json

{
  "singleValueExtendedProperties": [
      {
         "id":"String {66f5a359-4659-4830-9070-00047ec6ac6e} Name Color",
         "value":"Green"
      }
    ]
}
```

**Comment by codemasterover9000** [comment]
Yes we write Events with an attached extended property. In the MS library it goes something like this:

```
        SingleValueLegacyExtendedProperty extProp = new SingleValueLegacyExtendedProperty();
        extProp.id = EXTENDED_PROPERTY_ID;
        extProp.value = "...";

        Event event = new Event();
        event.singleValueExtendedProperties =
                new SingleValueLegacyExtendedPropertyCollectionPage(List.of(extProp), null);
```
We are not using the latest version of the library as we are looking to switch instead of upgrade so it may look a little different in the latest version.

**Comment by davidmoten** [comment]
I'll check the OData standard about how navigation properties are created. In the meantime you'll probably need to use the custom request above.

**Comment by codemasterover9000** [comment]
Ok thanks, I will take a look at using a custom event for now.

**Comment by davidmoten** [comment]
I just realized it is already there, a `post` method on collection requests. Try it out.

```java
SingleValueLegacyExtendedProperty p = SingleValueLegacyExtendedProperty //
                .builderSingleValueLegacyExtendedProperty() //
                .id("String {66f5a359-4659-4830-9070-00047ec6ac6e} Name Color") //
                .value("Green")
                .build();
Message m = client.me().messages("theId").get();
m.getSingleValueExtendedProperties().post(p);
```

**Comment by davidmoten** [comment]
Note that we might want a `patch` method too, not sure but will be easy to add.

**Comment by davidmoten** [comment]
adding the patch method now

**Comment by codemasterover9000** [comment]
Ok sounds good. 

> I'll check the OData standard about how navigation properties are created and when they are creatable (`ContainsTarget=true` is likely it). In the meantime you'll probably need to use the custom request above.

Would it eventually be possible to do this in a single request? As it's less error prone (atomic) and more performant/rate limit prone etc..

**Comment by davidmoten** [comment]
Probably. We'll just get it working first.

**Comment by davidmoten** [comment]
Right, becoming clearer now. On the read side navigation properties that are contained are just like normal properties but we need to pass `$expand` query parameter to return them. So not supported yet but I'll look at it (and the write side).

**Comment by davidmoten** [comment]
I've been reading further and I realized that `message.attachments` Navigation Property has `ContainsTarget=true` and both `attachment` and `singleValueLegacyExtendedProperty` are `EntityType` (rather than `ComplexType`). The email builder uses the method I quoted earlier, code is [here](https://github.com/davidmoten/odata-client/blob/9e92e8889343d7f8861e86afbd9859357c28300a/odata-client-msgraph/src/main/java/com/github/davidmoten/msgraph/Email.java#L299-L306) and I know it works, my old workplace uses it hundreds of times a day with arbitrary attachments.

Can you do a test for me to see if this code works? Use something other than Message if it suits you. 

```java
SingleValueLegacyExtendedProperty p = SingleValueLegacyExtendedProperty //
                .builderSingleValueLegacyExtendedProperty() //
                .id("String {66f5a359-4659-4830-9070-00047ec6ac6e} Name Color") //
                .value("Green")
                .build();
Message m = client.me().messages("theId").get();
m.getSingleValueExtendedProperties().post(p);
m.getSingleValueExtendedProperties().forEach(System.out::println);
```
I just want to get us to a place that works and then we can talk further about efficiency. Unfortunately I don't currently have access to a Microsoft Graph instance to do tests other than unauthenticated Graph Explorer which has no write access (and no 
 `singleValueExtendedProperties` present.

**Comment by davidmoten** [comment]
https://github.com/davidmoten/odata-client/pull/430 has been merged with full support for contained navigation properties (efficient). I'll address #423 and then build a release.

**Comment by davidmoten** [comment]
support in [0.1.93](https://github.com/davidmoten/odata-client/releases/tag/0.1.93) on Maven Central now

**Comment by codemasterover9000** [comment]
> ```java
> m.getSingleValueExtendedProperties().forEach(System.out::println);
> ```

I tested this using post with the following result:

```
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" com.github.davidmoten.odata.client.ClientException: responseCode=405 from url=https://graph.microsoft.com/v1.0/users/AdeleV%40test.onmicrosoft.com/calendar/events/singleValueExtendedProperties, expectedResponseCode in [200, 299], message=
{"error":{"code":"ErrorInvalidRequest","message":"The OData request is not supported."}}
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCode(RequestHelper.java:89)
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCode(RequestHelper.java:99)
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCodeOk(RequestHelper.java:94)
	at com.github.davidmoten.odata.client.internal.RequestHelper.submitAny(RequestHelper.java:186)
	at com.github.davidmoten.odata.client.internal.RequestHelper.postAny(RequestHelper.java:159)
	at com.github.davidmoten.odata.client.internal.RequestHelper.post(RequestHelper.java:131)
	at com.github.davidmoten.odata.client.CollectionPageEntityRequest.post(CollectionPageEntityRequest.java:60)
	at com.github.davidmoten.odata.client.CollectionEntityRequestOptionsBuilder.post(CollectionEntityRequestOptionsBuilder.java:199)
	at com.github.davidmoten.odata.client.CollectionPageEntityRequest.post(CollectionPageEntityRequest.java:97)
```

With patch:
```
Exception in thread "main" com.github.davidmoten.odata.client.ClientException: responseCode=400 from url=https://graph.microsoft.com/v1.0/users/AdeleV%40test.onmicrosoft.com/calendar/events/singleValueExtendedProperties, expectedResponseCode in [200, 299], message=
{"error":{"code":"RequestBodyRead","message":"A resource with type 'microsoft.graph.singleValueLegacyExtendedProperty' was found, but it is not assignable to the expected type 'microsoft.graph.event'. The type specified in the resource must be equal to either the expected type or a derived type."}}
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCode(RequestHelper.java:89)
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCode(RequestHelper.java:99)
	at com.github.davidmoten.odata.client.internal.RequestHelper.checkResponseCodeOk(RequestHelper.java:94)
	at com.github.davidmoten.odata.client.internal.RequestHelper.submitAny(RequestHelper.java:186)
	at com.github.davidmoten.odata.client.internal.RequestHelper.patchAny(RequestHelper.java:164)
	at com.github.davidmoten.odata.client.internal.RequestHelper.patch(RequestHelper.java:137)
	at com.github.davidmoten.odata.client.CollectionPageEntityRequest.patch(CollectionPageEntityRequest.java:64)
	at com.github.davidmoten.odata.client.CollectionEntityRequestOptionsBuilder.patch(CollectionEntityRequestOptionsBuilder.java:203)
	at com.github.davidmoten.odata.client.CollectionPageEntityRequest.patch(CollectionPageEntityRequest.java:101)
```

**Comment by davidmoten** [comment]
Thanks. Same result from Graph Explorer. Well, this is behaviour that differs from `message.attachments` for example even though they have the same definition in the odata metadata. An annoying deviation from the spec by Microsoft is my conclusion at the moment. 

That means that to deal with `singleValueExtendedProperties` you are forced to use a custom call or the new feature that I've put in (use `expand` to read the message with those properties, and message builders or mutators to post/patch). I assume this is how they deal with it in the Microsoft client. 

Can you try the new stuff and see if it suits your needs?

**Comment by davidmoten** [comment]
Ah more info. I see that Microsoft has been thinking about it. This [file](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/transformed_v1.0_metadata.xml) has metadata that looks like this:

```xml
        <NavigationProperty Name="attachments" Type="Collection(graph.attachment)" ContainsTarget="true" />
        <NavigationProperty Name="extensions" Type="Collection(graph.extension)" ContainsTarget="true" />
        <NavigationProperty Name="multiValueExtendedProperties" Type="Collection(graph.multiValueLegacyExtendedProperty)" ContainsTarget="true">
          <Annotation Term="Org.OData.Capabilities.V1.NavigationRestrictions">
            <Record>
              <PropertyValue Property="Navigability">
                <EnumMember>Org.OData.Capabilities.V1.NavigationType/None</EnumMember>
              </PropertyValue>
            </Record>
          </Annotation>
        </NavigationProperty>
        <NavigationProperty Name="singleValueExtendedProperties" Type="Collection(graph.singleValueLegacyExtendedProperty)" ContainsTarget="true">
          <Annotation Term="Org.OData.Capabilities.V1.NavigationRestrictions">
            <Record>
              <PropertyValue Property="Navigability">
                <EnumMember>Org.OData.Capabilities.V1.NavigationType/None</EnumMember>
              </PropertyValue>
            </Record>
          </Annotation>
        </NavigationProperty>
      </EntityType>
```
Using those Annotations I can avoid making network calls (and getting 405s) from those paths. The advice I gave doesn't change (which was to not make those calls) but I will at some point soon ensure those calls are not made at all.

**Comment by davidmoten** [comment]
I asked Microsoft [about it](https://github.com/microsoftgraph/msgraph-metadata/issues/609).

**Comment by codemasterover9000** [comment]
> I asked Microsoft [about it](https://github.com/microsoftgraph/msgraph-metadata/issues/609).

Aha part of the mystery solved then. 

I tested with `$expand` but can't seem  to get it to work not even with the official API. I can `$filter` on the extended properties so I know they're there. But can't can't get them returned directly with `$expand` for some reason. 

I tried `expand("singleValueExtendedProperties")` and `expand("singleValueExtendedProperties($select=id,value)")`. But there is nothing in the json response.

**Comment by davidmoten** [comment]
Can you show me the code you used?

**Comment by codemasterover9000** [comment]
I used this to test

```
        CollectionPage<Event> events = graphClient.users("test@test.onmicrosoft.com")
                .calendar()
                .events()
                .expand("singleValueExtendedProperties($select=id,value)")
                .get();

        events.forEach(System.out::println);
```

The url it uses is `https://graph.microsoft.com/v1.0/users/test%40test.onmicrosoft.com/calendar/events?$expand=singleValueExtendedProperties($select=id%2Cvalue)`

**Comment by codemasterover9000** [comment]
Tried both same result. But I think the it's the stackoverflow issue you mentioned. When I do:

```
        CollectionPage<Event> events = graphClient.users("test@test.onmicrosoft.com")
                .calendar()
                .calendarView()
                .query("StartDateTime", "...")
                .query("EndDateTime", "...")
                .expand("singleValueExtendedProperties($filter=id eq '...')")
                .get();
```
I actually get the extended properties

**Comment by davidmoten** [comment]
ah good, progress. Well I mark that as a problem with MsGraph not my release.

**Comment by codemasterover9000** [comment]
Do you have any idea when write support will be available?

**Comment by davidmoten** [comment]
write support already there with this change.  For example, an update of properties would be done like this:

```java
Message m = client.me().messages("theId").get();
m.withSingleValueExtendedProperties(props).patch();
```

**Comment by codemasterover9000** [comment]
Yes true. But I means meant atomic write support as in write a new message or event with extended properties using only one request.

**Comment by davidmoten** [comment]
If you mean add append one property to the existing properties in this scenario then I don't have a solution beyond a custom call (I'd have to check the msgraph reference to see what they suggest):

```java
Message m = client.me().messages("theId").get();
m.withSingleValueExtendedProperties(props).patch();
```

If you want to create a new message with singleValueExtendedProperties then you just use the builder and then 
```java
client.me().messages().post(message);
```

**Comment by codemasterover9000** [comment]
I'm missing something then I think. The code you posted above is the only way to create an event/message with extended properties as far as I see. 

> 
> ```java
> Message m = client.me().messages("theId").get();
> m.withSingleValueExtendedProperties(props).patch();
> ```

One request to create/get the event/message and one to add the extended properties

**Comment by codemasterover9000** [comment]
Perfect! Thanks

**Comment by davidmoten** [comment]
I'll close this off. Reopen it if something comes up.
