### ISSUE TITLE
$orderBy condition misspelled in query url

### ISSUE THREAD

**Issue by antonantonovich** [davidmoten/odata-client#435]
According to the https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionorderby orderby parameter should be spelled in lower case: "$orderby", not "$orderBy"

that's a minor issue as we have a workaround to make a call like ".query("$orderby", "LastModified desc").get()" but it would nice to have it in api-like way.

**Comment by davidmoten** [comment]
Thanks! I'll sort it

**Comment by davidmoten** [comment]
Thanks for the report. The fix is in [0.1.94](https://github.com/davidmoten/odata-client/releases/tag/0.1.94) on Maven Central now.
