### ISSUE TITLE
Expanding item attachments in attachment list

### ISSUE THREAD

**Issue by AmudhaNila** [davidmoten/odata-client#47]
Hi David,

I am trying to get the list of attachments in an email and get the details of each attachment with the $expand=microsoft.graph.itemattachment/item option to expand item details if present. However, the item details go under unmappedFields hash map and are not visible in the JSON response. I am not sure how to map it to an object as the type of item could vary. Could you please help me out with an example of how to include expanded item details as part of the response JSON?

```
Attachment attachmentDetails = OdataClientFactory
                    .request()
                    .users(emailId)
                    .mailFolders(folderId)
                    .messages(messageId)
                    .attachments(attachmentId)
                    .expand("microsoft.graph.itemattachment/item")
                    .get();
```

**Comment by davidmoten** [comment]
You are expecting an `ItemAttachment`? Cast attachmentDetails to ItemAttachment and then use its methods. Unlike the Microsoft java sdk odata-client supports the inheritance heirarchy.

**Comment by AmudhaNila** [comment]
Thanks for the quick response David. 
I am expecting an Attachment of any type and if it is an ItemAttachment, then the expanded details i.e. "Item" property as well. Is it possible to do this? Assuming I cast to ItemAttachment, could you help me understand how to get the JSON response with the Item details included?

**Comment by davidmoten** [comment]
Does casting work for getting access to the message details? Have you tried it?

What I mean is 

```java
Attachment attachmentDetails = OdataClientFactory
                    .request()
                    .users(emailId)
                    .mailFolders(folderId)
                    .messages(messageId)
                    .attachments(attachmentId)
                    .expand("microsoft.graph.itemattachment/item")
                    .get();
if (attachment instanceof ItemAttachment) {
    ItemAttachment a = (ItemAttachment) attachment;
    // do something with a
} else if (attachment instanceof FileAttachment) {
    FileAttachment a = (FileAttachment) attachment;
    // do something with a
} else {
    ReferenceAttachment a = (ReferenceAttachment) attachment;
    // do something with a
}
```

**Comment by davidmoten** [comment]
I just had a look at ItemAttachment and see that to get item field you have to do:

```java
ItemAttachment itemAttachment = (ItemAttachment) list.get(0);
// make another request to get the item
OutlookItem item = itemAttachment.getItem().get();
```
and of course you are hoping to skip that because the $expand option has already obtained the item field. There isn't direct support for that at the moment. I'll have a read of the specification and think about it.

**Comment by AmudhaNila** [comment]
Thanks David. That was exactly my concern. Meanwhile, I will try the getItem() call and get back to you.

**Comment by davidmoten** [comment]
I've just merged #48 to master that supports expand calls. 

```java
Attachment attachment = client
                    .users(emailId)
                    .mailFolders(folderId)
                    .messages(messageId)
                    .attachments(attachmentId)
                    .expand("microsoft.graph.itemattachment/item")
                    .get();
if (attachment instanceof ItemAttachment) {
    ItemAttachment a = (ItemAttachment) attachment;
    OutlookItem item = a.getItem().get();
    ...
} else if (attachment instanceof FileAttachment) {
    FileAttachment a = (FileAttachment) attachment;
    // do something with a
} else {
    ReferenceAttachment a = (ReferenceAttachment) attachment;
    // do something with a
}
```

When the above code is called, the line `OutlookItem item = a.getItem().get();` will not actually make a network call but rather use the json in unmapped fields of attachment. If the json is not present in the unmapped fields then a network call will be made.

Does that provide what you were looking for?

**Comment by davidmoten** [comment]
The change mentioned is in 0.1.37 on Maven Central now.

**Comment by AmudhaNila** [comment]
Thank you David for making the changes. I have tested it and it is working fine. However, I still need to retrieve the unmapped fields in the Outlook Item and the key values vary for different outlook items. So, I am currently analyzing the possibility of storing the response as a string and simply use it to add those attachments later on to messages. I understand that I have to objectify the string to an outlook item at that time. Or, is there a way to just use a JSON string to post an attachment to a message using the odata client?

**Comment by davidmoten** [comment]
>I understand that I have to objectify the string to an outlook item at that time. Or, is there a way to just use a JSON string to post an attachment to a message using the odata client?

You can do both. See `client._custom()` for making raw calls to the API, and you can use `Serializer.INSTANCE` to move from object to json and back.

**Comment by AmudhaNila** [comment]
Thanks David. I chose the client._custom() way and it works as expected.

**Comment by AmudhaNila** [comment]
Hi David, I just saw your recent commit adding a withUnmappedField method to FileAttachment. I was actually looking for something similar for ItemAttachment so that I can attach an outlook item to a message. Do you plan to add similar functionality for ItemAttachment as well?

**Comment by davidmoten** [comment]
Yes, for all generated classes. It will be in the next release, probably within 24 hours.

**Comment by davidmoten** [comment]
0.1.38 is now on Maven Central and includes the `withUnmappedField()` method on generated classes.

**Comment by AmudhaNila** [comment]
Thanks David. Will check it out.

**Comment by davidmoten** [comment]
> Thanks David. Will check it out.

FYI improvements in _custom() are in master now, see #52
