### ISSUE TITLE
Retrieve events with calendarView

### ISSUE THREAD

**Issue by madanbisht** [davidmoten/odata-client#49]
Hi David,
    As per [MS Graph API](https://docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http), startdatetime & enddatetime are required parameters for 'calendarView' API. Can you please suggest how to pass startdatetime & enddatetime parameters in the below 'calendarView' request?

```
graphServiceObject()
.users(mailId)
.calendars(calendarId)
.calendarView()
.delta()
.stream();
```

**Comment by davidmoten** [comment]
Use `.query`, here's an example:
```java
client 
        .me() 
        .calendar()
        .calendarView() 
        .query("startDateTime", "2019-11-08T19:00:00-08:00") //
        .query("endDateTime", "2019-11-10T19:00:00-08:00") //
        .get();
```

**Comment by madanbisht** [comment]
Thanks David, seems .query() is generic, we tested and its working fine.

**Comment by madanbisht** [comment]
One more query please, email is successfully getting created as below:

```
        Message response = graphserviceobject()
                    .users(emailId)
                    .mailFolders(folderId)
                    .messages()
                    .post(content);
```
**Its urgent and it will be great if you can suggest how to add below property while creating mail message?**
```
"SingleValueExtendedProperties": [
        {
            "PropertyId": "SystemTime 0x0E06",
            "Value": "2020-09-15T09:55:38.7169+11:00"
        }
]
```

**Comment by davidmoten** [comment]
Hmm, I wouldn't rely on this because generated objects are supposed to be immutable, however you can probably do:

```java
Map<String, Object> map = new HashMap<>();
map.put("PropertyId", "SystemTime 0x0E06");
map.put("Value", "2020-09-15T09:55:38.7169+11:00");
List<Object> list = Arrays.asList(map);
content.getUnmappedFields().put("SingleValueExtendedProperties", list);
```
before posting content.

**Comment by davidmoten** [comment]
I did a quick test and I don't think the unmapped fields get serialized for the post. That might need fixing. The other way you can do this is via a `client._custom()` call where you can use raw json as you need.

**Comment by davidmoten** [comment]
I think I've got the fix that should enable the use of UnmappedFields as above. It's committed to master now. You can pull the latest and do `mvn clean install` and then use the SNAPSHOT dependency to test if you like. I will actually support immutability properly soon so the code will change for this but it will still be possible.

**Comment by davidmoten** [comment]
For your info the code above will probably look like this when I fix mutability of UnmappedFields:

```java
Map<String, Object> map = new HashMap<>();
map.put("PropertyId", "SystemTime 0x0E06");
map.put("Value", "2020-09-15T09:55:38.7169+11:00");
List<Object> list = Arrays.asList(map);
content = content.withUnmappedField("SingleValueExtendedProperties", list);
```

**Comment by madanbisht** [comment]
Thank you so much for your quick response, we will verify and reopen this ticket if required.

Thanks once again....:)

**Comment by davidmoten** [comment]
0.1.38 is now on Maven Central and `UnmappedFields` is no longer mutable so you need to use this approach (or `client._custom()` of course):

```java
Map<String, Object> map = new HashMap<>();
map.put("PropertyId", "SystemTime 0x0E06");
map.put("Value", "2020-09-15T09:55:38.7169+11:00");
List<Object> list = Arrays.asList(map);
content = content.withUnmappedField("SingleValueExtendedProperties", list);
```
