### ISSUE TITLE
Calendar Event Attributes

### ISSUE THREAD

**Issue by madanbisht** [davidmoten/odata-client#55]
Hi David,
   Can you please help us on the below request?
    transactionId is one of the attribute in a calendar event, currently this attribute is not available in Event.class(odata.msgraph.client.entity). In our use case this attribute is required, is it possible to include transactionId attribute?

**Below are the event attributes from MS Graph API.**
```
{
	"@odata.type": "#microsoft.graph.event",
	"@odata.etag": "W/\"21tPFP6RokilGqK6dhLjjwAAWGHb1w==\"",
	"createdDateTime": "2020-09-23T17:31:22.3683256Z",
	"transactionId": "c8bd03c3-2b4b-214e-5a23-82b132a73e41",
	"originalStartTimeZone": "India Standard Time",
         ..............
         <other attributes>
}
```

**Comment by davidmoten** [comment]
I don't understand. `odata.msgraph.client.entity.Event` has a `getTransactionId()` method. If you set logging to debug level you can see all interaction with the service and all json. Are you telling me that the `transactionId` field is not present in the json?

**Comment by davidmoten** [comment]
I see this from Graph documentation https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0#properties:

>A custom identifier specified by a client app for the server to avoid redundant POST operations in case of client retries to create the same event. This is useful when low network connectivity causes the client to time out before receiving a response from the server for the client's prior create-event request. After you set transactionId when creating an event, you cannot change transactionId in a subsequent update. **This property is only returned in a response payload if an app has set it**. Optional.

**Comment by madanbisht** [comment]
> I don't understand. `odata.msgraph.client.entity.Event` has a `getTransactionId()` method. If you set logging to debug level you can see all interaction with the service and all json.

> Are you telling me that the `transactionId` field is not present in the json?

Yes, 'transactionId' is missing in the response from below query.
```
graphservice().
                 .users(mailId)
                 .calendars(calendarId)
                 .calendarView()
                 .delta()
                 .query("startDateTime",startDateTime).query("endDateTime",endDateTime)
                 .streamWithDeltaLink();
```

**Comment by madanbisht** [comment]
Oops.. It seems its added in recent builds. Just now tried Build 0.1.39 and transactionId is included in the response.

Thanks David,
