### ISSUE TITLE
API to get mailboxsettings

### ISSUE THREAD

**Issue by madanbisht** [davidmoten/odata-client#57]
Hi David, Good Morning...!!!
   We are trying to get mailboxsettings using odata but didn't find any API and below is the corresponding graph API. Is it possible to add?

https://graph.microsoft.com/v1.0/users/{user}/mailboxsettings

**Comment by davidmoten** [comment]
Peculiar, I'll check it out...

**Comment by davidmoten** [comment]
It's there:
```java
client.users("123").get().getMailboxSettings();
```

**Comment by davidmoten** [comment]
BTW latest version is 0.1.41

**Comment by davidmoten** [comment]
Ah, I think I see a bug. If I do this:
```java
GraphService client = MsGraph.explorer().build();
System.out.println(client.me().get().getMailboxSettings());
```
I get 
```
Optional.empty
```
but if I do:
```java
GraphService client = MsGraph.explorer().build();
System.out.println(client.me().select("mailboxSettings").get().getMailboxSettings());
```
I get
```
Optional[MailboxSettings[archiveFolder=AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OAAuAAAAAAAiQ8W967B7TKBjgx9rVEURAQAiIsqMbYjsT5e-T7KzowPTAAAAAAFNAAA=, automaticRepliesSetting=AutomaticRepliesSetting[externalAudience=ALL, externalReplyMessage=, internalReplyMessage=, scheduledEndDateTime=DateTimeTimeZone[dateTime=2020-10-07T07:00:00.0000000, timeZone=UTC],unmappedFields={},odataType=null, scheduledStartDateTime=DateTimeTimeZone[dateTime=2020-10-06T07:00:00.0000000, timeZone=UTC],unmappedFields={},odataType=null, status=DISABLED],unmappedFields={},odataType=null, dateFormat=M/d/yyyy, delegateMeetingMessageDeliveryOptions=SEND_TO_DELEGATE_ONLY, language=LocaleInfo[displayName=English (United States), locale=en-US],unmappedFields={},odataType=null, timeFormat=h:mm tt, timeZone=Pacific Standard Time, workingHours=WorkingHours[daysOfWeek=[MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY], endTime=17:00, startTime=08:00, timeZone=TimeZoneBase[name=Pacific Standard Time],unmappedFields={},odataType=null],unmappedFields={},odataType=null],unmappedFields={},odataType=null]
```
I'll chase it down.

**Comment by davidmoten** [comment]
So *odata-client-msgraph* is behaving itself but according to the OData [spec](https://docs.oasis-open.org/odata/odata/v4.01/os/part1-protocol/odata-v4.01-os-part1-protocol.html#sec_RequestingIndividualProperties) you should just be able to call `client.me().mailboxSettings().get()`. I'll have a look at that in a bit. First I'll try and find out how the user should know when to add `.select("X")` to get the expanded property.

**Comment by davidmoten** [comment]
Ah, it's not a bug, this is expected behaviour. 

From https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http:

>Note: Getting a user returns a default set of properties only (businessPhones, displayName, givenName, id, jobTitle, mail, mobilePhone, officeLocation, preferredLanguage, surname, userPrincipalName). Use $select to get the other properties and relationships for the user object.

**Comment by madanbisht** [comment]
Thanks below works fine.
```
                        graphObject()
                            .users(mailid)
                            .select("mailboxSettings")
                            .get()
                            .getMailboxSettings());
```
