### ISSUE TITLE
usage of postStringReturnsString() returns "Method Not Allowed"

### ISSUE THREAD

**Issue by abhishekthetechguy** [davidmoten/odata-client#64]
Hello David

Hope you are doing fine.

As part of my project, I wrote an api that is using the `_custom()` method to execute a request( I am trying to acheive json batching here). The concerned piece of code is as below

`                    .map(graphService -> graphService
                            ._custom()
                            .postStringReturnsString(url, batchContent, RequestOptions.EMPTY, RequestHeader.contentType(MediaType.APPLICATION_JSON_VALUE))));
`

This was working with version `0.1.40` of the odata client and was giving the expected response but after bumping the version to `0.1.41`, I am getting error response with status as `METHOD_NOT_ALLOWED`. I have tested the scenario with version `0.1.40` and there hasn't been any change in my part of the code since then. 

The complete response looks as below
`{
    "timestamp": "2020-10-08T13:12:30.453+00:00",
    "path": "/api/o365/v1/users/mail-folders/batch",
    "status": "METHOD_NOT_ALLOWED",
    "error": "Method Not Allowed",
    "message": "responseCode=405 from url=https://graph.microsoft.com/v1.0/$batch, expectedResponseCode in [200, 299], message=\n{\r\n  \"error\": {\r\n    \"code\": \"UnknownError\",\r\n    \"message\": \"Method not allowed\",\r\n    \"innerError\": {\r\n      \"date\": \"2020-10-08T13:12:30\",\r\n      \"request-id\": \"476267ba-8baf-48cb-ad5c-823154a52922\",\r\n      \"client-request-id\": \"476267ba-8baf-48cb-ad5c-823154a52922\"\r\n    }\r\n  }\r\n}",
    "requestId": "804939a3-1",
    "statusCode": 405
}`

Could you please advise if there has been change from version `0.1.41` on-wards and if I need to use some other method to achieve this now?

Regards
Abhishek

**Comment by davidmoten** [comment]
Thanks, I'll take a look.

**Comment by davidmoten** [comment]
There was a typo in `HttpService.submitWithContent` where a POST was using PUT hence the METHOD_NOT_ALLOWED error. I'll fix now.

**Comment by abhishekthetechguy** [comment]
Thanks David

**Comment by davidmoten** [comment]
The fix is in version 0.1.42 on Maven Central now.

**Comment by abhishekthetechguy** [comment]
Thanks David. Tested with 0.1.42 and its working fine. Closing the issue now.

Regards
Abhishek
