### ISSUE TITLE
POST call not working for MS batch api

### ISSUE THREAD

**Issue by abhishekthetechguy** [davidmoten/odata-client#73]
Hello David 

I believe this is perhaps related to issue #64 .
While trying to execute an unit test that targets [https://graph.microsoft.com/v1.0/$batch](url) on MS side via `_custom()` method, I am getting a `POST request not expected` error. 

Concerned code that I am trying to execute:
---------------------------------------------

`
graphService = com.mf.dp.edgeservice.o365.utilities.GraphServiceMock.
                       CreateGraphServiceMockObject("/$batch",
                        getUnitTestFileValidUserMailFoldersByBatch,
                        RequestHeader.ODATA_VERSION,
                        RequestHeader.ACCEPT_JSON_METADATA_MINIMAL);
`

`
        var mailFoldersList = graphService._custom().postStringReturnsString(ConfigurationService.getMSGraphBatchRequestURI(), mockedBatchContent, RequestOptions.EMPTY, RequestHeader.contentType(MediaType.APPLICATION_JSON_VALUE));
`

mockedBatchContent has a valid string already populated in it. The same thing works when tried through an actual graph service object( not a mock one).

Error call stack:
---------------

Calling:
POST
  https://graph.microsoft.com/v1.0/$batch
  Content-Type=application/json

java.lang.RuntimeException: POST request not expected for url=https://graph.microsoft.com/v1.0/$batch, headers=[[name=Content-Type, value=application/json]]

	at com.github.davidmoten.odata.client.TestingService$BuilderBase$1.post(TestingService.java:295)
	at com.github.davidmoten.odata.client.HttpService.submitWithContent(HttpService.java:89)
	at com.github.davidmoten.odata.client.HttpService.submitWithContent(HttpService.java:100)
	at com.github.davidmoten.odata.client.CustomRequest.submitStringReturnsString(CustomRequest.java:126)
	at com.github.davidmoten.odata.client.CustomRequest.postStringReturnsString(CustomRequest.java:92)

From what I could understand, the POST call is not being recognized in the TestingService class for the concerned end point.
Could you please check this ?

Regards
Abhishek

**Comment by davidmoten** [comment]
I see this line:

```{"requests":[{"id":"1","method":"GET","url":"/users/Shubham@dataprotector19.onmicrosoft.com"}]}```

which says when you created the expected calls the POST method was not specified. Can you show me the code that creates the expected calls?

**Comment by abhishekthetechguy** [comment]
Hi David

I got it working. I was not setting the POST call correctly when building the mock object. Hence the error. Sorry for the trouble. Because of  the recent issue with `_custom()` that we had, I felt that this could be similar. I should have troubleshooted more on my side. Hope you don't mind it too much. I am going to close this now.

Regards
Abhishek
