### ISSUE TITLE
patchOrPut method always return  204 if success in TestingService class

### ISSUE THREAD

**Issue by nashikanta** [davidmoten/odata-client#99]
Hi David,

While testing "**graphService._service().put(ConfigurationService.getContactPhotoURI(mailid, contactid),
                                    requestHeaderList, inputStream, rawContent.length, RequestOptions.EMPTY)**", I am expecting different HttpResponse code. But It always return 204 if success. I think it should be configuration as TestingService.ContainerBuilder allow us to mock responseStatusCode as well as shown below code

clientBuilder()
                .expectRequest(path)
                .withMethod(HttpMethod.PUT)
                .withPayload(payLoadResource)
                .withResponseStatusCode(200)
                .withRequestHeaders(requestHeaders)
                .build();

Can you please fix it.

**Comment by davidmoten** [comment]
TestingService exists just to support the project unit tests but I'll have a look anyway.

**Comment by davidmoten** [comment]
This is the advice from the odata specification on response codes for PATCH and PUT:

https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_CommonResponseStatusCodes

It is advice of course so a real service call may return a different response code. What response code are you expecting in this case?

**Comment by nashikanta** [comment]
I am expecting different HttpResponses. In one of the testing, I was expecting 200 as real service call also return 200.
It would be more flexible if we could make it customizable through withResponseStatusCode() TestingService client builder.

**Comment by davidmoten** [comment]
setting the response code for patch and put should work now in 0.1.49 on Maven Central now. Try it out.

**Comment by nashikanta** [comment]
Thanks David. Worked as expected
